---
settings:
  name: Contributor's Guide
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,de-de,es-es,fr-fr,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Contribuire al contenuto
    url: "/index.html"
  - title: Style per documenti NetApp
    url: "/style.html"
  - title: Riferimento AsciiDoc
    url: "/asciidoc_syntax.html"
  - title: Policy sui contenuti generati dall'ai
    url: "/ai-policy.html"
  - title: Note legali
    url: "/legal-notices.html"
